# Site settings
baseurl: ""
url: "https://gohyojun15.github.io"

title: "Hyojun Go"
description: "Hyojun Go's personal academic homepage featuring research and publications."
keywords: "Hyojun Go, academic homepage, research, publications, 3D generation, diffusion models"

# Build settings
markdown: kramdown

google_analytics: G-WPC3V6T2G6

collections:
  - publications
  - news

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - vendor/
